gcp_project_id: daniel-azuma-com-1
gcp_project_number: "561558629009"
gcp_function_name: sanctuary-bot
secret_name: sanctuary-bot
lookup_command: word
help_command: help
# discord_guild_id: "828125771288805436" # DTS
discord_guild_id: "822929633208434758" # Sanctuary
